### ISSUE TITLE
USER STORY : Set-up GitHub repository

### ISSUE THREAD

**Issue by tomik-z-cech** [tomik-z-cech/PP4-Aneta-s-Glimmer#1]
As a **Developer**, I need to set-up a repository on GitHub platform to be able to have control over versions of project.

**Acceptance Criteria :**

Working GitHub repository.

**Tasks :**
- [x] Create new repository - PP4 - Aneta's Glimmer
- [x] Create project for the same repository
- [x] Create labels for importance (Must, Should, Could, Won't Have)
- [x] Create labels for Story Points
- [x] Create Epic's
- [x] Create User Stories

**Epic : **
[EPIC 1](https://github.com/tomik-z-cech/PP4-Aneta-s-Glimmer/issues/4)
