### ISSUE TITLE
USER STORY : Define Database Schema and create sub apps.

### ISSUE THREAD

**Issue by tomik-z-cech** [tomik-z-cech/PP4-Aneta-s-Glimmer#13]
As a Developer, I need to create databse schema that fits the purpose of the project and also create all the modular apps that will be used in the project.

**Acceptance Criteria :**

All Django apps are created and database schema in place to stick to.

**Tasks :**

- [x] Create Landing app + models
- [x] Create News app + models
- [x] Create Artists app + models
- [x] Create Bookings app + models
- [x] Create Profile Manager app + models
- [x] Create Styles app + models
- [x] Create Database Schema that shows names of tables, fileds and relationships

**Epic :**
[EPIC 2](https://github.com/tomik-z-cech/PP4-Aneta-s-Glimmer/issues/12)

**Comment by tomik-z-cech** [comment]
All models created in commit [1202424](https://github.com/tomik-z-cech/PP4-Aneta-s-Glimmer/commit/12024248cc53b3966b70377388984862bfc50c0b).

Database schema [link](https://github.com/tomik-z-cech/PP4-Aneta-s-Glimmer/blob/main/docs/db-schema.png).
