### ISSUE TITLE
USER STORY : Create database realtionships

### ISSUE THREAD

**Issue by tomik-z-cech** [tomik-z-cech/PP4-Aneta-s-Glimmer#14]
As a Developer, I need to define relatinships between models and import the relationships into working apps models.

**Acceptance Criteria :**

All models are working with the relationships defined, all models that are related to other app models are linked via import statements.

**Tasks :**

- [x] Create models for all apps.
- [x] Set relationships between them via import statements (if applicable).
- [x] Connect with ElephantSQL server via URL given by ElephantSQL
- [x] Connect with Cloudinary server via URL given by Cloudinary
- [x] Run `python manage.py makemigrations`
- [x] Run `python manage.py migrate`

**Epic :**
[EPIC 2](https://github.com/tomik-z-cech/PP4-Aneta-s-Glimmer/issues/12)

**Comment by tomik-z-cech** [comment]
All models sucefully set in commit [1202424](https://github.com/tomik-z-cech/PP4-Aneta-s-Glimmer/commit/12024248cc53b3966b70377388984862bfc50c0b).
