### ISSUE TITLE
USER STORY : Implement Data Validation in Models

### ISSUE THREAD

**Issue by tomik-z-cech** [tomik-z-cech/PP4-Aneta-s-Glimmer#15]
As a Developer, I need implement data validation rules within Glimmer database models.

**Acceptance Criteria :**

All values insrted to database are the correct values and types, all applicable fileds are all set to be required or/and to be unique or/and nullable/not nullable.

**Tasks :**

- [x] Set correct data type for all fileds
- [x] Set all required fields to `required = True`
- [x] Set all required fileds that can be nullable to `null = True`
- [x] Set all required fileds that have to be unique (username) `unique = True`
- [x] Create SuperUser
- [x] Test data type by inserting test data into databse

**Epic :**
[EPIC 2](https://github.com/tomik-z-cech/PP4-Aneta-s-Glimmer/issues/12)

**Comment by tomik-z-cech** [comment]
All models sucefully set in commit [1202424](https://github.com/tomik-z-cech/PP4-Aneta-s-Glimmer/commit/12024248cc53b3966b70377388984862bfc50c0b).
