### ISSUE TITLE
USER STORY : Log In

### ISSUE THREAD

**Issue by tomik-z-cech** [tomik-z-cech/PP4-Aneta-s-Glimmer#18]
As a **Site User** I am able to **Log In** to **see registered user section.**

**Acceptance Criteria :**

*1.Registered user :*
When I visit the site then I am able to login via login link.

*2.Not registered user :*
When I visit the site and trying to log in then I am given error message that user does not exist.

**Tasks :**

- [x] Create login link on landing page
- [x] Test functionality trying to login with not existing credentials
- [x] Create a test user
- [x] Test functionality with valid credentials

**Epic :**
[EPIC 3](https://github.com/tomik-z-cech/PP4-Aneta-s-Glimmer/issues/16)
