### ISSUE TITLE
USER STORY : Reset my password if forgotten

### ISSUE THREAD

**Issue by tomik-z-cech** [tomik-z-cech/PP4-Aneta-s-Glimmer#19]
As a **Site User** I am able to **Reset My Password** to **change my password if forgotten**.

**Acceptance Criteria :**

When I visit login page then I have the option to reset my password via provided link and email with reset link is sent to me.

**Tasks :**

- [x] Register with mail client (Gmail) 
- [x] Set up all relevant settings for sending emails in `settings.py`
- [x] Test functinality with valid credentails
- [x] Test functionality with invalid credentials

**Epic :**
[EPIC 3](https://github.com/tomik-z-cech/PP4-Aneta-s-Glimmer/issues/16)

**Comment by tomik-z-cech** [comment]
Email functionality set in commit [491242a](https://github.com/tomik-z-cech/PP4-Aneta-s-Glimmer/commit/491242a472f186f75c15335507cfe605ef1d5dbd).
