### ISSUE TITLE
USER STORY : Create working Django App

### ISSUE THREAD

**Issue by tomik-z-cech** [tomik-z-cech/PP4-Aneta-s-Glimmer#2]
As a Developer, I need to install all dependencies, correctly set settings.py and create working app in local environment.

**Acceptance Criteria :**

All dependencies are installed, settings.py all set for local view and when project is ran locally, symbol of correctly set app is shown (rocket).

**Tasks :**

- [x] Install Django
- [x] Install Psycopg2
- [x] Install Cloudinary
- [x] Install dj-database
- [x] Insatll AllAuth
- [x] Install Crispy Forms
- [x] Create first app called "bookings"
- [x] Set-up settings.py

**Epic :**
[EPIC 1](https://github.com/tomik-z-cech/PP4-Aneta-s-Glimmer/issues/4)

**Comment by tomik-z-cech** [comment]
Done in commit [251e391](https://github.com/tomik-z-cech/PP4-Aneta-s-Glimmer/commit/b606c30f5658763d01e6535726f4a4d92d4ce0e0)
