### ISSUE TITLE
USER STORY : Change Details (Phone Nuber, Email Address, etc.)

### ISSUE THREAD

**Issue by tomik-z-cech** [tomik-z-cech/PP4-Aneta-s-Glimmer#22]
As a **Site User** I can **Update My Detail** to **be able to manage my account in case of changes**.

**Acceptance Criteria :**

*1. Logged in user :*
When I login then I can clearly navigate to "My Details" section where I can change my details.

*2. Not logged in user :*
Don't have that option as not logged in.

**Tasks :**

- [x] Create a view in `profilemanager` app.
- [x] Read current details from User model
- [x] Create a template for the view.
- [x] Create a form in template
- [x] Create a link to AllAuth email change (as emails are verified)
- [x] Create a link to AllAuth password change
- [x] Test functionality with valid credentials

**Epic :**
[EPIC 4](https://github.com/tomik-z-cech/PP4-Aneta-s-Glimmer/issues/20)

**Comment by tomik-z-cech** [comment]
This was done in commit[1f168ee](https://github.com/tomik-z-cech/PP4-Aneta-s-Glimmer/commit/1f168eeb43330c02cb3ad79931c84002e46a5ede).
