### ISSUE TITLE
USER STORY : Delete my account

### ISSUE THREAD

**Issue by tomik-z-cech** [tomik-z-cech/PP4-Aneta-s-Glimmer#23]
As a **Site User** I can **Delete My Account** to **be able to opt out from all services**.

**Acceptance Criteria :**

*1. Logged in user :*
When I navigate to "my details" then I have the option of delete my account entirely.

*2. Not logged in user :*
Don't have that option as not logged in.

**Tasks :**

- [x] Update `views.py` in `profilemanager` app
- [x] Update template (delete button)
- [x] Create a modal that informs user of the deletition
- [x] Test functionality with valid credentials

**Epic :**
[EPIC 4](https://github.com/tomik-z-cech/PP4-Aneta-s-Glimmer/issues/20)

**Comment by tomik-z-cech** [comment]
This was done in commit[1f168ee](https://github.com/tomik-z-cech/PP4-Aneta-s-Glimmer/commit/1f168eeb43330c02cb3ad79931c84002e46a5ede).
