### ISSUE TITLE
USER STORY : See News Highlights on landing page

### ISSUE THREAD

**Issue by tomik-z-cech** [tomik-z-cech/PP4-Aneta-s-Glimmer#25]
As a **Site User** I can **See the News Highlights** to **see three newest news posts**.

**Acceptance Criteria :**

When I visit the site's landing page then I am able to see news highlights on a carousel rotation.

**Tasks :**

- [x] Create function in `views.py` that filters all news posts by published/not published. 
- [x] Adjust the same function to filter the same list of post from newest and only 3 posts.
- [x] Create a carousel view in `index.html`
- [x] Create a default message when no posts to show
- [x] Test functionality with 0, 1, 2, 3 or more posts in database.

**Epic :**
[EPIC 5](https://github.com/tomik-z-cech/PP4-Aneta-s-Glimmer/issues/24)

**Comment by tomik-z-cech** [comment]
Done in commit [503f6ab](https://github.com/tomik-z-cech/PP4-Aneta-s-Glimmer/commit/503f6ab884226ae2453e5598ae5792f19e83788d).
