### ISSUE TITLE
USER STORY : See list of all News & Details

### ISSUE THREAD

**Issue by tomik-z-cech** [tomik-z-cech/PP4-Aneta-s-Glimmer#26]
As a **Site User** I can **Visit Page with all News** to be able to**see all News**.

**Acceptance Criteria :**

*Regsitered and Not registered user :*
When I visit the site's landing page then I am comfortably able to navigate to list of all news and see details of each news posts.

**Tasks :**

- [x] Create view for list of all news with slug fields in `views.py`
- [x] Create template for list of news of news `all_news.html` 
- [x] Create view for details of news post in `views.py`
- [x] Create template for news detail `news_detail.html`
- [x] Adjust `urls.py` accordingly
- [x] Test functionality with valid credentials

**Epic :**
[EPIC 5](https://github.com/tomik-z-cech/PP4-Aneta-s-Glimmer/issues/24)

**Comment by tomik-z-cech** [comment]
This was done in commit [503f6ab](https://github.com/tomik-z-cech/PP4-Aneta-s-Glimmer/commit/503f6ab884226ae2453e5598ae5792f19e83788d).
