### ISSUE TITLE
USER STORY : Like/Unlike News

### ISSUE THREAD

**Issue by tomik-z-cech** [tomik-z-cech/PP4-Aneta-s-Glimmer#27]
As a **Site User** I can **Like or Unlike News Post** to **highlight the News Post as interesting**.

**Acceptance Criteria :**

*Logged in user :*
When I open news post detail then I am able to like or unlike the post.

*Not logged in user :*
Doesn't have that option.

**Tasks :**

- [x] Create view in `views.py`
- [x] Create a like/dislike button in `news_detail.html`
- [x] Create if/else statement in `news_detail.html` that this function is only available for logged in users
- [x] Test functionality as logged in user
- [x] Test functionality as not logged in user

**Epic :**
[EPIC 5](https://github.com/tomik-z-cech/PP4-Aneta-s-Glimmer/issues/24)

**Comment by tomik-z-cech** [comment]
This was done in commit [11010d4](https://github.com/tomik-z-cech/PP4-Aneta-s-Glimmer/commit/11010d40fbe33d667ee6804c4869e5ae96aeeb7c).
