### ISSUE TITLE
USER STORY : Comment on News

### ISSUE THREAD

**Issue by tomik-z-cech** [tomik-z-cech/PP4-Aneta-s-Glimmer#28]
As a **Site User** I can **Comment on News Post** to **share my opinion**.

**Acceptance Criteria :**

*Logged in user :*
When I open news post detail then I am able to add comment on the relevant news post.

*Not logged in user :*
Doesn't have that option.

**Tasks :**

- [x] Adjust news post view in `views.py` with `def post`
- [x] Create commenting form in `news_details.html`
- [x] Provide user with "submit comment" button
- [x] Only add the form visibility to logged in users
- [x] Test functionality as logged in user
- [x] Test functionality as not logged in user

**Epic :**
[EPIC 5](https://github.com/tomik-z-cech/PP4-Aneta-s-Glimmer/issues/24)

**Comment by tomik-z-cech** [comment]
This was done in commit [a42b417](https://github.com/tomik-z-cech/PP4-Aneta-s-Glimmer/commit/a42b4178dacdd64c00b0bbb532e20f1fe75ab06f).
