### ISSUE TITLE
USER STORY : See other users Comments

### ISSUE THREAD

**Issue by tomik-z-cech** [tomik-z-cech/PP4-Aneta-s-Glimmer#29]
As a **Site User** I can **see other comments on News Posts** to **read other Users opinions**.

**Acceptance Criteria :**

*Logged in user :*
When I open news post detail then I am able to see other people comments.

*Not logged in user :*
Doesn't have that option.

**Tasks :**

- [x] Adjuts `views.py`
- [x] Create "comments section" in `news_details.html`
- [x] Iterate through comments to display them in `news_details.html`
- [x] Ensure the comments visibility is only for logged in users
- [x] Paginate the comments
- [x] Test functionality as logged in user
- [x] Test functionality as not logged in user

**Epic :**
[EPIC 5](https://github.com/tomik-z-cech/PP4-Aneta-s-Glimmer/issues/24)

**Comment by tomik-z-cech** [comment]
This was done in commit [a823dfc](https://github.com/tomik-z-cech/PP4-Aneta-s-Glimmer/commit/a823dfc321ea432c1fe688e19e6739187d252c0a).
