### ISSUE TITLE
USER STORY : Deploy to Heroku

### ISSUE THREAD

**Issue by tomik-z-cech** [tomik-z-cech/PP4-Aneta-s-Glimmer#3]
As a Developer I need to create a working Heroku deployement.

**Acceptance Criteria :**

Working Heroku Deployment, when first deployed site accesed, it gives hint of correctly installed Django App (DEBUG = True). Create if statement in settings.py for DEBUG = False when deployed.

**Tasks :**

- [x] Create Heroku App
- [x] Link with GitHub
- [x] Set up Vars
- [x] Create first deployment
- [x] Fix issues (if any)
- [x] Set DEBUG = False

**Epic :**
[EPIC 1](https://github.com/tomik-z-cech/PP4-Aneta-s-Glimmer/issues/4)

**Comment by tomik-z-cech** [comment]
If statement for DEBUG = False added in commit [cca2ec2](https://github.com/tomik-z-cech/PP4-Aneta-s-Glimmer/commit/cca2ec26e07aaf9676052fa4a2db3a2be50f366a)
