### ISSUE TITLE
USER STORY : See who else liked

### ISSUE THREAD

**Issue by tomik-z-cech** [tomik-z-cech/PP4-Aneta-s-Glimmer#30]
As a **Site User** I can **see who else liked News Posts** to **see who else has the same opinion**.

**Acceptance Criteria :**

*Logged in user :*
When I open news post detail then I am able to see who else liked the post.

*Not logged in user :*
Doesn't have that option.

**Tasks :**

- [x] Filter users they liked the same post in `views.py`
- [x] Create a section in `news_details.html`
- [x] Create `for` loop to itarate through users that liked the post
- [x] Ensure this option is only available for logged in users
- [x] Create `if` statement that if many people like, the initial display will be 2 username + "amount of others"
- [x] Test functionality as logged in user
- [x] Test functionality as not logged in user

**Epic :**
[EPIC 5](https://github.com/tomik-z-cech/PP4-Aneta-s-Glimmer/issues/24)

**Comment by tomik-z-cech** [comment]
This was done in commit [7b09a2e](https://github.com/tomik-z-cech/PP4-Aneta-s-Glimmer/commit/7b09a2ec75cffb8656d34d00b1f34a49b5374161).
