### ISSUE TITLE
USER STORY : List of Styles

### ISSUE THREAD

**Issue by tomik-z-cech** [tomik-z-cech/PP4-Aneta-s-Glimmer#32]
As a **Site User** I can **See list of available styles** to **be able to choose one to see details**.

**Acceptance Criteria :**

*Logged in & Not logged in user :*
When I navigate to styles from navbar then I see list of all styles that are available.

**Tasks :**

- [x] Create "styles" app
- [x] Adjust project `urls.py`
- [x] Create view in `views.py` to source all styles data from database including slug field
- [x] Include Artists model in `views.py` to create a link between styles and artists
- [x] Create template `styles.html`
- [x] Test functionality as logged in or not logged in user

**Epic :**
[EPIC 6](https://github.com/tomik-z-cech/PP4-Aneta-s-Glimmer/issues/31)

**Comment by tomik-z-cech** [comment]
This was done in commit [f989ca8](https://github.com/tomik-z-cech/PP4-Aneta-s-Glimmer/commit/f989ca83477ccde96828399d58d3fffe0a949450).
