### ISSUE TITLE
USER STORY : Styles Details

### ISSUE THREAD

**Issue by tomik-z-cech** [tomik-z-cech/PP4-Aneta-s-Glimmer#33]
As a **Site User** I can **See Style details** to **see description and what artist does this particular style**.

**Acceptance Criteria :**

When I open list of styles then I like to be able to see all details about the particular style including likes and "tries".

**Tasks :**

- [x] Adjust `views.py` for detail list of styles
- [x] Create `style_detail.html` template
- [x] Maintain link between styels and artists
- [x] Source data from database of who does like
- [x] Source data from database of who likes to try
- [x] Test functionality as logged in user
- [x] Test functionality as not logged in user

**Epic :**
[EPIC 6](https://github.com/tomik-z-cech/PP4-Aneta-s-Glimmer/issues/31)

**Comment by tomik-z-cech** [comment]
All styles details done in commit [9e5415a](https://github.com/tomik-z-cech/PP4-Aneta-s-Glimmer/commit/9e5415a8102cb5d27f315315407267ae87e3cbc4).
