### ISSUE TITLE
USER STORY : Like / Unlike Styles

### ISSUE THREAD

**Issue by tomik-z-cech** [tomik-z-cech/PP4-Aneta-s-Glimmer#34]
As a **Site User** I can **Like / Unlike particular Style** to **express my opinion**.

**Acceptance Criteria :**

*Logged in user :*
When I open detail of a particular style then I am able to like/unlike style.

*Not logged in user :*
Doesn't have that option.

**Tasks :**

- [x] Adjust `views.py`
- [x] Provide user with "like/unlike" button in `style_detail.html`
- [x] Test functionality as logged in user
- [x] Test functionality as not logged in user

**Epic :**
[EPIC 6](https://github.com/tomik-z-cech/PP4-Aneta-s-Glimmer/issues/31)

**Comment by tomik-z-cech** [comment]
This was done in commit [b22d266](https://github.com/tomik-z-cech/PP4-Aneta-s-Glimmer/commit/b22d266264181a63874720aa066c9c87c3ff4b1b).
