### ISSUE TITLE
USER STORY : See who else likes the particular Style

### ISSUE THREAD

**Issue by tomik-z-cech** [tomik-z-cech/PP4-Aneta-s-Glimmer#35]
As a **Site User** I can **see who else liked the particular style** to **see who else has same opinion**.

**Acceptance Criteria :**

*Logged in user :*
When I open style detail then I am able to see who else liked the style.

*Not logged in user :*
Doesn't have that option.

**Tasks :**

- [x] Filter users they liked the same style in `views.py`
- [x] Create a section in `style_details.html`
- [x] Create `for` loop to itarate through users that liked the style
- [x] Ensure this option is only available for logged in users
- [x] Create `if` statement that if many people like, the initial display will be 2 username + "amount of others"
- [x] Test functionality as logged in user
- [x] Test functionality as not logged in user

**Epic :**
[EPIC 6](https://github.com/tomik-z-cech/PP4-Aneta-s-Glimmer/issues/31)

**Comment by tomik-z-cech** [comment]
This was done in commit [9e5415a](https://github.com/tomik-z-cech/PP4-Aneta-s-Glimmer/commit/9e5415a8102cb5d27f315315407267ae87e3cbc4).
