### ISSUE TITLE
USER STORY : Mark / Unmark Styles as "Wan't to try"

### ISSUE THREAD

**Issue by tomik-z-cech** [tomik-z-cech/PP4-Aneta-s-Glimmer#36]
As a **Site User** I can **Mark / Unmark particular style** to **express my interest**.

**Acceptance Criteria :**

*Logged in user :*
When I open detail of a particular style then I am able to mark it as "try/untry".

*Not logged in user :*
Doesn't have that option.

**Tasks :**

- [x] Adjust `views.py`
- [x] Provide user with "try/untry" button in `style_detail.html`
- [x] Test functionality as logged in user
- [x] Test functionality as not logged in user

**Epic :**
[EPIC 6](https://github.com/tomik-z-cech/PP4-Aneta-s-Glimmer/issues/31)

**Comment by tomik-z-cech** [comment]
This was done in commit [b22d266](https://github.com/tomik-z-cech/PP4-Aneta-s-Glimmer/commit/b22d266264181a63874720aa066c9c87c3ff4b1b).
