### ISSUE TITLE
USER STORY : Create a booking

### ISSUE THREAD

**Issue by tomik-z-cech** [tomik-z-cech/PP4-Aneta-s-Glimmer#39]
As a **Site User** I can **Create new booking** and to **be able to choose date, time and artist**.

**Acceptance Criteria :**

*Logged in user :*
When I navigate to "my bookings" then I am able to create a booking.

*Not logged in user :*
Doesn't have that option.

**Tasks :**

- [x] Create view in `views.py`
- [x] Create and link URL's
- [x] Create template `new_booking.html`
- [x] Let user to select date, time, artist and style
- [x] Send notification to user when booking confirmed
- [x] Create function with AJAX to control user's selection
- [x] Create JS script to pop up next field when previous selected
- [x] Control users booking choices, so wrong combination can't be selected
- [x] Test functionality as logged in user
- [x] Test functionality as not logged in user 

**Epic :**
[EPIC 7](https://github.com/tomik-z-cech/PP4-Aneta-s-Glimmer/issues/38)

**Comment by tomik-z-cech** [comment]
This was done in commit [a817445](https://github.com/tomik-z-cech/PP4-Aneta-s-Glimmer/commit/a817445b3fd1c8c5fc891bcee4b777a1f83972a4).
