### ISSUE TITLE
EPIC 1 : Environment Configuration

### ISSUE THREAD

**Issue by tomik-z-cech** [tomik-z-cech/PP4-Aneta-s-Glimmer#4]
**Description:** This epic focuses on configuring environment and initaial Heroku deployment.

**Details :**

- [x] [USER STORY : Set up GiHub repository](https://github.com/users/tomik-z-cech/projects/1/views/1?pane=issue&itemId=44330601)
- [x] [USER STORY : Create working Django app](https://github.com/users/tomik-z-cech/projects/1/views/1?pane=issue&itemId=44330650)
- [x] [USER STORY : Deploy to Heroku](https://github.com/users/tomik-z-cech/projects/1/views/1?pane=issue&itemId=44330691)

**Comment by tomik-z-cech** [comment]
This epic closed in commit [44d641d](https://github.com/tomik-z-cech/PP4-Aneta-s-Glimmer/commit/44d641d7e96154806b15ee5dfc0a06289f5601e7).
