### ISSUE TITLE
USER STORY : See my bookings

### ISSUE THREAD

**Issue by tomik-z-cech** [tomik-z-cech/PP4-Aneta-s-Glimmer#40]
As a **Site User** I can **See all my bookings** to **be able to keep record of them**.

**Acceptance Criteria :**

*Logged in user :*
When I navigate to "My bookings", I can clearly see upcoming and past bookings.

*Not logged in user :*
Doesn't have that option.

**Tasks :**

- [x] Update `views.py`
- [x] Create a section in `bookings.html` template
- [x] Provide user clearly with section of past bookings
- [x] Provide user clearly with section of upcoming bookings
- [x] Test functionality as logged in user
- [x] Test functionality as not logged in user

**Epic :**
[EPIC 7](https://github.com/tomik-z-cech/PP4-Aneta-s-Glimmer/issues/38)

**Comment by tomik-z-cech** [comment]
This was done in commit [0893feb](https://github.com/tomik-z-cech/PP4-Aneta-s-Glimmer/commit/0893feb43f831438ef9f3503e409d8f4c9d49c7b).
