### ISSUE TITLE
USER STORY : Update my bookings

### ISSUE THREAD

**Issue by tomik-z-cech** [tomik-z-cech/PP4-Aneta-s-Glimmer#41]
As a **Site User** I can **Update any of my future bookings** to **change details**.

**Acceptance Criteria :**

*Logged in user :*
When I navigate to "My Bookings" then I am able to select a booking that I wan to change.

*Not logged in user :*
Doesn't have that option.

**Tasks :**

- [x] Provide user with "Edit booking" button in list of bookings
- [x] Update `views.py`
- [x] Update URL's
- [x] Provide the user with same logic as in when creating booking so wrong combination style-artist-date-time can't be chosen
- [x] Test functionality as logged in user
- [x] Test functionality as not logged in user

**Epic :**
[EPIC 7](https://github.com/tomik-z-cech/PP4-Aneta-s-Glimmer/issues/38)

**Comment by tomik-z-cech** [comment]
This was done in commit [1ab529e](https://github.com/tomik-z-cech/PP4-Aneta-s-Glimmer/commit/1ab529e66fe125bfab99fe14c65e45a7f758af10).
