### ISSUE TITLE
USER STORY : Delete my bookings

### ISSUE THREAD

**Issue by tomik-z-cech** [tomik-z-cech/PP4-Aneta-s-Glimmer#42]
As a **Site User** I can **Delete any of my future bookings** to **cancel the booking**.

**Acceptance Criteria :**

*Logged in user :*
When I navigate to my bookings then I can cancel the booking(s).

*Not logged in user :*
Doesn't have that option.

**Tasks :**

- [x] Provide user with button "Cancel booking"
- [x] Provide user with alert to confirm their selection
- [x] Update `views.py`
- [x] Provide user wit email confirmation of booking cancelled
- [x] Test functionality as logged in user
- [x] Test functionality as not logged in user

**Epic :**
[EPIC 7](https://github.com/tomik-z-cech/PP4-Aneta-s-Glimmer/issues/38)

**Comment by tomik-z-cech** [comment]
This was done in commit [74d849c](https://github.com/tomik-z-cech/PP4-Aneta-s-Glimmer/commit/74d849cdd3887da3019f13dc34ee4799ed6ef771).
