### ISSUE TITLE
USER STORY : Leave review after booking finished

### ISSUE THREAD

**Issue by tomik-z-cech** [tomik-z-cech/PP4-Aneta-s-Glimmer#43]
As a **Site User** I can **leave review**  to **let the others know about my satisfaction**.

**Acceptance Criteria :**

*Logged in user :*
When my booking is done I can navigate to "My bookings" and leave a review for particular booking.

*Not logged in user :*
Doesn't have that option.

**Tasks :**

- [x] Provide user with email info to leave a review when booking status changed to "done"
- [x] Provide user with scale 1-5 on "My bookings" page for each review than can be reviewed
- [x] Ensure each booking can only be reviewed once
- [x] Ensure that only booking marked "done" by admin can be reviewed
- [x] Test functionality as logged in user
- [x] Test functionality as not logged in user

**Epic :**
[EPIC 7](https://github.com/tomik-z-cech/PP4-Aneta-s-Glimmer/issues/38)

**Comment by tomik-z-cech** [comment]
This was done in comit [0ff4da1](https://github.com/tomik-z-cech/PP4-Aneta-s-Glimmer/commit/0ff4da14bc3eecb6ab818efe9883789a81cf3a26).
