### ISSUE TITLE
USER STORY : Get confirmation of my booking being approved

### ISSUE THREAD

**Issue by tomik-z-cech** [tomik-z-cech/PP4-Aneta-s-Glimmer#44]
As a **Site User** I get **confirmation email when my booking is approved** to **be sure the booking is going ahead**.

**Acceptance Criteria :**

When I my booking is confirmed by **Site Admin** then I am notified via email.

**Tasks :**

- [x] Update `admin.py`
- [x] Create message provided
- [x] Source user email
- [x] Test functionality as Site Admin

**Epic :**
[EPIC 7](https://github.com/tomik-z-cech/PP4-Aneta-s-Glimmer/issues/38)

**Comment by tomik-z-cech** [comment]
This was done in commit [8e4ef41](https://github.com/tomik-z-cech/PP4-Aneta-s-Glimmer/commit/8e4ef412be0228a064f9bc9d698b4c8fc402f14c).
