### ISSUE TITLE
USER STORY : Log out

### ISSUE THREAD

**Issue by tomik-z-cech** [tomik-z-cech/PP4-Aneta-s-Glimmer#48]
As a **Site User**, I am able to log out to **leave the site functions for registered users**.

**Acceptance Criteria :**

*1.Registered user :*
When I am logged in then I am able to logout.

*2.Not registered user :*
Don't have that option.

**Tasks :**

- [x] Create a log out link in base.html
- [x] Create if statement `{% if user.is_authenticated %}` in `base.html`
- [x] Test functionality with valid credentials

**Epic :**
[EPIC 3](https://github.com/tomik-z-cech/PP4-Aneta-s-Glimmer/issues/16)
