### ISSUE TITLE
USER STORY : Create search bar on landing page

### ISSUE THREAD

**Issue by tomik-z-cech** [tomik-z-cech/PP4-Aneta-s-Glimmer#52]
As a **Site User** I am able to **use search function** through Artists, Styles and News to **quickly find what am I looking for**.

**Acceptance Criteria :**

When I open the landing page then I can see the search bar.

**Tasks :**

- [x] Create search logic in `views.py` in landing app.
- [x] Provide users clearly with what fields they are searching
- [x] Provide user with search button
- [x] User shouldn't be able to submit empty string as search criteria
- [x] Test functionality

**Epic :**
[EPIC 8](https://github.com/tomik-z-cech/PP4-Aneta-s-Glimmer/issues/51)

**Comment by tomik-z-cech** [comment]
This was done in commit [0c9cebe](https://github.com/tomik-z-cech/PP4-Aneta-s-Glimmer/commit/0c9cebea491867384d9fc385f5f1e34935bba0ce).
