### ISSUE TITLE
USER STORY : Delete user

### ISSUE THREAD

**Issue by tomik-z-cech** [tomik-z-cech/PP4-Aneta-s-Glimmer#55]
As a **Site Admin**, I can **delete user accounts** that are no longer in use to make sure my database of clients is up to date.

**Acceptance Criteria :**

When I log in to admin suite then I can navigate to user profiles and delte user entirely.

**Tasks :**

- [x] Create UserProfile Model
- [x] Register the model within django admin
- [x] Add display fields and sort fields
- [x] Test functionality as Site Admin

**Epic :**
[EPIC 9](https://github.com/tomik-z-cech/PP4-Aneta-s-Glimmer/issues/54)

**Comment by tomik-z-cech** [comment]
This was done in commit [3bf93b4](https://github.com/tomik-z-cech/PP4-Aneta-s-Glimmer/commit/3bf93b4f0ab84850a9181d9d96973adcbd8a7b66).
