### ISSUE TITLE
USER STORY : Manage available styles

### ISSUE THREAD

**Issue by tomik-z-cech** [tomik-z-cech/PP4-Aneta-s-Glimmer#57]
As a **Site Admin**, I can **add available styles** to keep content up to date.

**Acceptance Criteria :**

When I log in to admin suite then I can navigate to Styles and add, change or delete available styles.

**Tasks :**

- [x] Create Styles Model
- [x] Register the model within django admin
- [x] Add display fields and sort fields
- [x] Add Cloudinary filed to store imagery content
- [x] Test functionality as Site Admin

**Epic :**
[EPIC 9](https://github.com/tomik-z-cech/PP4-Aneta-s-Glimmer/issues/54)

**Comment by tomik-z-cech** [comment]
This was done in commit [3bf93b4](https://github.com/tomik-z-cech/PP4-Aneta-s-Glimmer/commit/3bf93b4f0ab84850a9181d9d96973adcbd8a7b66).
