### ISSUE TITLE
USER STORY : Mark bookings as confirmed

### ISSUE THREAD

**Issue by tomik-z-cech** [tomik-z-cech/PP4-Aneta-s-Glimmer#60]
As a **Site Admin**, I can **mark bookings as confirmed** to inform user of the progress.

**Acceptance Criteria :**

When I log in to admin suite then I can navigate to Bookings and mark pending bookings as confirmed.

**Tasks :**

- [x] Create Bookings Model
- [x] Register the model within django admin
- [x] Add display fields and sort fields
- [x] Add quick action - mark as confirmed
- [x] Ensure this function only works on pending bookings
- [x] Test functionality as Site Admin

**Epic :**
[EPIC 9](https://github.com/tomik-z-cech/PP4-Aneta-s-Glimmer/issues/54)

**Comment by tomik-z-cech** [comment]
This was done in commit [3bf93b4](https://github.com/tomik-z-cech/PP4-Aneta-s-Glimmer/commit/3bf93b4f0ab84850a9181d9d96973adcbd8a7b66).
