### ISSUE TITLE
USER STORY : Last-minute bookings

### ISSUE THREAD

**Issue by tomik-z-cech** [tomik-z-cech/PP4-Aneta-s-Glimmer#62]
As a **Site Admin**, I **need to provide** users with "last-minute" bookings available to let them know how many slots are free the following day.

**Acceptance Criteria :**
*Logged in user :*
When **Site Users** log in and navigate to "My Bookings" then they are provided with info of the following day free slots.

*Not logged in user :*
Doesn't have that option.

**Tasks :**

- [x] Adjust `views.py` in bookings app
- [x] Display info containing name of artist
- [x] Create logic to count how many free slots left today (depends on time of the day and existing bookings)
- [x] Display info containg free slots per artist today
- [x] Create logic to count how many free slots left following business day (depends on existing bookings)
- [x] Display info containg free slots per artist following business day
- [x] Test this function as logged in user
- [x] Test this function as not logged in user

**Epic :**
[EPIC 9](https://github.com/tomik-z-cech/PP4-Aneta-s-Glimmer/issues/54)

**Comment by tomik-z-cech** [comment]
This was done in commit [7bb09fb](https://github.com/tomik-z-cech/PP4-Aneta-s-Glimmer/commit/7bb09fb6b273ce873b23350cf89df2387bb26d62).
