### ISSUE TITLE
USER STORY : Intuitive navigation

### ISSUE THREAD

**Issue by tomik-z-cech** [tomik-z-cech/PP4-Aneta-s-Glimmer#71]
As a **Site Developer**, I need to insure easy navigation throughout the site

**Acceptance Criteria :**

When user does access the site then all links and actions are intuitive and don't need too much thinking, design is responsive on all device sizes.

**Tasks :**

- [x] Style Landing Page
- [x] Style News
- [x] Style Styles
- [x] Style Team
- [x] Style Bookings
- [x] Style My Profile
- [x] Style Forms
- [x] Style Modals
- [x] Test design as logged in user
- [x] Test design as not logged in user
- [x] Test responsiveness as logged in or not logged in user

**Epic :**
[EPIC 10](https://github.com/tomik-z-cech/PP4-Aneta-s-Glimmer/issues/70)

**Comment by tomik-z-cech** [comment]
The issue closed in commit [5d6e9e0](https://github.com/tomik-z-cech/PP4-Aneta-s-Glimmer/commit/5d6e9e0abade05103117adf7c058e36ee0616919).
