### ISSUE TITLE
USER STORY : Color scheme

### ISSUE THREAD

**Issue by tomik-z-cech** [tomik-z-cech/PP4-Aneta-s-Glimmer#72]
As a **Site Developer**, I need to insure same color scheme throughout the site

**Acceptance Criteria :**

When user does access the site then all pages rendered are sticking to same color scheme as it does improve UX.

**Tasks :**

- [x] Color Landing Page
- [x] Color News
- [x] Color Styles
- [x] Color Team
- [x] Color Bookings
- [x] Color My Profile
- [x] Color Forms
- [x] Color Modals
- [x] Check design as logged in user
- [x] Check design as not logged in user

**Epic :**
[EPIC 10](https://github.com/tomik-z-cech/PP4-Aneta-s-Glimmer/issues/70)

**Comment by tomik-z-cech** [comment]
The issue closed in commit [5d6e9e0](https://github.com/tomik-z-cech/PP4-Aneta-s-Glimmer/commit/5d6e9e0abade05103117adf7c058e36ee0616919).
