### ISSUE TITLE
USER STORY : WAVE compatibility

### ISSUE THREAD

**Issue by tomik-z-cech** [tomik-z-cech/PP4-Aneta-s-Glimmer#73]
As a **Site Developer**, I need to insure that site can be easily navigated using page readers, so it doen't have WAVE issues.

**Acceptance Criteria :**

When user does access the site using the page reader then the info provided does match the info provided graphically.

**Tasks :**

- [x] W3C - Landing Page
- [x] W3C - News
- [x] W3C - Styles
- [x] W3C - Team
- [x] W3C - Bookings
- [x] W3C - My Profile
- [x] W3C - Forms
- [x] W3C - Modals
- [x] Test W3C as logged in user
- [x] Test W3C as not logged in user
- [x] Test W3C on different device sizes

**Epic :**
[EPIC 10](https://github.com/tomik-z-cech/PP4-Aneta-s-Glimmer/issues/70)

**Comment by tomik-z-cech** [comment]
The issue closed in commit [5d6e9e0](https://github.com/tomik-z-cech/PP4-Aneta-s-Glimmer/commit/5d6e9e0abade05103117adf7c058e36ee0616919).
