### ISSUE TITLE
EPIC 3 : User Authentication and Authorization

### ISSUE THREAD

**Issue by tomik-z-cech** [tomik-z-cech/PP4-Aneta-s-Glimmer#8]
**Description:** This epic focuses on user authentication and authorization.

**Details :**

- [ ] [Implement user registration ](https://github.com/users/tomik-z-cech/projects/1/views/1?pane=issue&itemId=44332947)
- [ ] [Develop Log-In functionality](https://github.com/users/tomik-z-cech/projects/1/views/1?pane=issue&itemId=44333000)
- [ ] [Set up role-based access control](https://github.com/users/tomik-z-cech/projects/1/views/1?pane=issue&itemId=44333051)
